homepage:
    pattern:  /
    defaults: { _controller: PelshoffBlogBundle:Default:index }

article:
    pattern:  /{year}/{month}/{article}
    defaults: { _controller: PelshoffBlogBundle:Default:article }
    requirements:
        year:   \d+
        month:  \d+

about:
    pattern: /about
    defaults: { _controller: PelshoffBlogBundle:About:index }